### ISSUE TITLE
can't import this project to Dev c++

### ISSUE THREAD

**Issue by marwanes** [ixartz/Markov-segmentation#1]
help plz

**Comment by ixartz** [comment]
I have never tried to import this project to Dev c++, I used only Xcode on Mac

**Comment by marwanes** [comment]
there is other way to compile it ?
could u give me the makefile

**Comment by ixartz** [comment]
You can find a lot information in the README.md file:
https://github.com/ixartz/Markov-segmentation/blob/master/README.md

In this file, there is a section explaining how to compile the project:

> Building
> 
> The project uses CMake build system:
> 
> mkdir build && cd build
> cmake .. && make

**Comment by marwanes** [comment]
i read it but i can't compile it
how can i use CMake 
mkdir build && cd build
cmake .. && make

**Comment by marwanes** [comment]
could you give me a version for dev C++  i need it for a presentation

**Comment by ixartz** [comment]
CMake will generate a makefile for you
You just need to install Cmake on your machine

**Comment by marwanes** [comment]
now i have the project and CMake
 i
1/choose the code source "Markov-segmentation-master\src"
2/choose where to build it 
3/ i clicke generete 
put it doesn't work it give me "project files may be invalid " No CMAKE_C_COMPILER could be found
how can i fixe it

**Comment by ixartz** [comment]
CMake is a well documented tool, you will find all information you need on Internet

**Comment by marwanes** [comment]
now i have the project and CMake 
how can i build it 
1/choose the sorce code "Markov-segmentation-master/src"
2/choose the where to build and the compliler
3/ generte 
but it give me errors "project files may be invalide"

**Comment by ixartz** [comment]
It seems you solve your issue. Indeed, instead choosing "Markov-segmentation-master/src" as the source code, you should directly choose "Markov-segmentation-master" (without src/)
