### ISSUE TITLE
Error in there are multiple ways that an object of this type can be called with these arguments	

### ISSUE THREAD

**Issue by BALAJIELUMALAI** [ixartz/Markov-segmentation#2]
Error	6	error C3066: there are multiple ways that an object of this type can be called with these arguments	markov-segmentation-master\src\cost.cpp 40

mean_[classe](k) = sum / (image.cols * image.rows);   // the third variable shows the error is k
        covariance_[classe](k, k) = (sum2 - (sum * sum) / (image.cols * image.rows))
                                    / (image.cols * image.rows); // the third variable shows the error is (k,k)

Error	4	error C2144: syntax error : 'double' should be preceded by ';'	markov-segmentation-master\src\config.h	21

static constexpr double beta = 1.5;
    static constexpr double initial_temperature = 10.0;
    static constexpr double temperature_decrease = 0.95;
    static constexpr double min_change = 2.0;
above lines shows the error

**Comment by ixartz** [comment]
Which compiler you use? And which version?

**Comment by BALAJIELUMALAI** [comment]
Hi,
 I'm using visual studio 2013

**Comment by ixartz** [comment]
constexp is not available on visual studio 2013. I suggest that you update to a newer version 2015 or 2017 (maybe ?).

**Comment by BALAJIELUMALAI** [comment]
Thanks for the reply but my application is already developed in visual
studio 2013 for past 2 years still running but some new corrections there.
So please suggest me there is any way to solve.

**Comment by ixartz** [comment]
Remove constexp in the code. But, I really do not know if it will work or not.

**Comment by BALAJIELUMALAI** [comment]
Thanks I check it

**Comment by LiuHao-THU** [comment]
hi, i am also confused in calculating variance. the equation should be \sum{f_s - \mu_lambda}^2, however in your code, this equation is sum2 - sum* sum.

**Comment by LiuHao-THU** [comment]
I have found this...
https://stackoverflow.com/questions/2341340/calculate-mean-and-variance-with-one-iteration
